### ISSUE TITLE
Controller delete logic

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/cluster-api-provider-docker#150]
Related to #136. Also see https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/148#discussion_r310252990

The controller logic in https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/148 needs to handle cluster deletions in the `Reconcile` function.

**Comment by ericzhang08** [comment]
1. delete docker container when a machine be deleted.
2. unregister from ELB

**Comment by chuckha** [comment]
Oh one more thing I forgot, you will also need to ensure `kubeadm reset` gets called on the node. v1.15+ will offer `kubeadm reset` as a phase that updates the cluster's config map and v1.14 and below we will simply have to run `kubeadm reset` on the node as the command. I think this logic is already baked into the provider, but should be double checked.


This is necessary because docker reuses IPs as soon as they are available. WIthout this cleanup the cluster config map that kubeadm keeps track of has IPs that no longer exist as nodes and then it cannot add new nodes that reuse those same stale IPs.
