### ISSUE TITLE
This is nice on linux and unfriendly on os x

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#69]
/kind bug

**What steps did you take and what happened:**
Containers must talk to each other. Containers can talk to each other over their container IP address. Containers live in the docker0 network. My laptop cannot use the container IP to communicate with containers as the docker0 network is not bridged. Therefore my laptop can only talk to containers over localhost. The containers cannot talk to each other over localhost. Therefore the secret that contains the kube-apiserver's endpoint will only contain one value and will be wrong for either the remote ref controller or the host both of which are required to work.

This is a non-issue on linux since the docker0 network is bridged to my local network.

**Comment by fabriziopandini** [comment]
@chuckha what about:
1. storing two version of the kubeconfig file in the secret (the current + 1 mac friendly)
2. upgrade instruction to use `data.value-mac` instead of `data.value`

As an alternative to 2, it would be nice to have `capdctl config` subcommand that hides all this complexity to the users

**Comment by chuckha** [comment]
Closing in favor of https://github.com/kubernetes-sigs/cluster-api/issues/1685

/close
